services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - app_network

  socket_server_1:
    build: .
    develop:
      watch:
        - path: ./server.js
          action: sync+restart
          target: /app/server.js
          ignore:
            - node_modules
    container_name: socket_server_1
    networks:
      - app_network

  socket_server_2:
    build: .
    develop:
      watch:
        - path: ./server.js
          action: sync+restart
          target: /app/server.js
          ignore:
            - node_modules
    container_name: socket_server_2
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: socket_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - socket_server_1
      - socket_server_2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
